INSERT INTO departments (dept_name)
VALUES  ("Sales"),
        ("Accounting"),
        ("Human Resources"),
        ("Marketing"),
        ("Legal"),
        ("Engineering"),
        ("Warehousing"),
        ("Research and Development"),
        ("Software Engineering"),
        ("Customer Service");

INSERT INTO roles (role_title, role_salary, dept_id)
VALUES  ("Social Media Coordinator", 40000, 4),
        ("Customer Service Representative", 40000, 10),
        ("Accountant", 85000, 2),
        ("Internal Counsel", 12000, 5),
        ("Web Developer", 80000, 9),
        ("Staffing Manager", 100000, 3),
        ("Secretary", 30000, 3),
        ("Sales Associate", 40000, 1),
        ("Foreman", 75000, 6),
        ("Senior Research Chemist", 150000, 8),
        ("Chemist", 80000, 8),
        ("Inventory Manager", 50000, 7),
        ("Loader", 25000, 7),
        ("Forklift Operator", 40000, 7),
        ("Manufacturing Engineer", 45000, 6);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES  ("Bob", "Robertson", 1, 11),
        ("Andrew", "Drewer", 15, 14),
        ("Mark", "Marsh", 2, 11),
        ("Trish", "Rich", 14, 8),
        ("Barb", "Barnaby", 3, 11),
        ("Reggie", "Levy", 13, 8),
        ("Don", "Yukon", 4, 7),
        ("Percy", "Burburry", 12, 8),
        ("Lacy", "Jake-Waverly", 5, 11),
        ("Kevin", "Evans", 11, 12),
        ("Mitch", "Pritchard", 6, 11),
        ("Rachel", "Grace-Abel", 10, 12),
        ("Emily", "Bellamy", 7, 11),
        ("Winston", "Livingston", 9, 14),
        ("Brenda", "Menendez-Lendra", 8, 11),
        ("Bill", "Miller", 8, 11),
        ("Larry", "Harrison", 1, 11),
        ("Alice", "Vallon-Raleigh", 1, 11),
        ("Cooper", "Tibideux", 13, 8),
        ("Fred", "Armistead", 2, 11),
        ("Linda", "Panimba", 7, 11),
        ("Sarah", "Barrow-Sinclair", 11, 12),
        ("Chris", "Amethyst-Pisner", 11, 12),
        ("Rodger", "Dodge", 5, 11),
        ("Hank", "Banks", 14, 8);